apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ethnode
spec:
  template:
    spec:
      containers:
        - name: geth-rrr
          env:
            - name: BOOTNODE_PUB0
              valueFrom:
                configMapKeyRef:
                  name: ethnode-cfg
                  key: BOOTNODE_PUB0
            - name: BOOTNODE_HOST0
              valueFrom:
                configMapKeyRef:
                  name: ethnode-cfg
                  key: BOOTNODE_HOST0
