apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wild-nodes-iona-thaumagen-io
spec:
  commonName: "iona.thaumagen.io"
  secretName: wild-nodes-iona-thaumagen-io
  dnsNames:
    - "iona.thaumagen.io"
    - "*.iona.thaumagen.io"
  issuerRef:
    name: letsencrypt-staging-primary-dns
    kind: ClusterIssuer
